create table orders
(
    id                    varchar primary key not null,
    transaction_id        varchar,
    remote_id             varchar,
    status                varchar,
    exchange              varchar             not null,
    pair                  varchar             not null,
    base_asset            varchar             not null,
    quote_asset           varchar             not null,
    side                  varchar             not null,
    order_type            varchar             not null,
    enforcement           varchar,
    base_qty              float,
    quote_qty             float,
    price                 float,
    stop_price            float,
    iceberg_qty           float,
    is_test               boolean             not null,
    asset_type            varchar             not null,
    executed_qty          float,
    cummulative_quote_qty float,
    margin_side_effect: varchar,
    borrowed_amount: float,
    borrowed_asset: float,
    fills: json,
    weighted_price: float not null,
    total_executed_qty: float not null,
    rejection_reason: json,
    created_at: timestamp not null,
    updated_at: timestamp not null,
    closed_at: timestamp,
)
