create table orders
(
    id                    varchar primary key not null,
    transaction_id        varchar,
    remote_id             varchar,
    status                TEXT                not null,
    exchange              varchar             not null,
    pair                  varchar             not null,
    base_asset            varchar             not null,
    quote_asset           varchar             not null,
    side                  varchar             not null,
    order_type            varchar             not null,
    enforcement           varchar,
    base_qty              DOUBLE PRECISION,
    quote_qty             DOUBLE PRECISION,
    price                 DOUBLE PRECISION,
    stop_price            DOUBLE PRECISION,
    iceberg_qty           DOUBLE PRECISION,
    is_test               boolean             not null,
    asset_type            varchar             not null,
    executed_qty          DOUBLE PRECISION,
    cummulative_quote_qty DOUBLE PRECISION,
    margin_side_effect    varchar,
    borrowed_amount       DOUBLE PRECISION,
    borrowed_asset        varchar,
    fills                 varchar             not null,
    weighted_price        DOUBLE PRECISION    not null,
    total_executed_qty    DOUBLE PRECISION    not null,
    rejection_reason      varchar,
    created_at            datetime            not null,
    updated_at            datetime            not null,
    closed_at             datetime
);
