table! {
    orders (id) {
        id -> Text,
        transaction_id -> Nullable<Text>,
        remote_id -> Nullable<Text>,
        status -> Text,
        exchange -> Text,
        pair -> Text,
        base_asset -> Text,
        quote_asset -> Text,
        side -> Text,
        order_type -> Text,
        enforcement -> Nullable<Text>,
        base_qty -> Nullable<Double>,
        quote_qty -> Nullable<Double>,
        price -> Nullable<Double>,
        stop_price -> Nullable<Double>,
        iceberg_qty -> Nullable<Double>,
        is_test -> Bool,
        asset_type -> Text,
        executed_qty -> Nullable<Double>,
        cummulative_quote_qty -> Nullable<Double>,
        margin_side_effect -> Nullable<Text>,
        borrowed_amount -> Nullable<Double>,
        borrowed_asset -> Nullable<Text>,
        fills -> Text,
        weighted_price -> Double,
        total_executed_qty -> Double,
        rejection_reason -> Nullable<Text>,
        created_at -> Timestamp,
        updated_at -> Timestamp,
        closed_at -> Nullable<Timestamp>,
    }
}
