@namespace("livefeeds")
protocol Simple {
  enum TradeType {
    BUY,
    SELL
  }

  record LiveTrade {
      long event_ms;
      string pair;
      double amount;
      double price;
      int tt;
  }

  record LiveOrder {
      long event_ms;
      double amount;
      string pair;
      double price;
      int tt;
  }

  record Orderbook {
    long event_ms;
    string pair;
    // [(Price, Volume)...]
    array<array<double>> asks;
    array<array<double>> bids;
  }
}
