@namespace("livefeeds")
protocol Simple {
  enum TradeType {
    BUY,
    SELL
  }

  record LiveTrade {
      long event_ms;
      string pair;
      double amount;
      double price;
      int tt;
  }

  record LiveOrder {
      long event_ms;
      double amount;
      string pair;
      double price;
      int tt;
  }

  record Orderbook {
    long event_ms;
    string pair;
    // [(Price, Volume)...]
    array<array<double>> asks;
    array<array<double>> bids;
  }

  record Candle {
    long event_ms;
    string pair;
    long start_ms;
    long end_ms;
    double open;
    double high;
    double low;
    double close;
    double volume;
    double quote_volume;
    long trade_count;
  }
}
